### PR TITLE
Fix a few typos

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Review by fonsp — APPROVED** [review]

**Comment by fonsp** [comment]
🎉 Thanks a million!

**Comment by pitmonticone** [comment]
Thank you @fonsp for making all these great resources publicly available for free.

**Comment by fonsp** [comment]
You are super welcome!! Are you currently taking the course? Or using the material in your own teaching?

**Comment by pitmonticone** [comment]
I was just consulting this material to familiarise with Pluto notebooks for my future presentations and teaching in combination with Quarto and Jupyter notebooks.

**Pull request merged**
