### PR TITLE
Fixed error in hw1.jl

### PR DESCRIPTION
**Pull request by lemonade5117**
Fixed definition of gaussian distribution: Wrapped 2πσ^2 in square root

### CODE REVIEW

**Comment by lemonade5117** [comment]
I wasn't able to fix the error in hw1.html though

**Comment by lemonade5117** [comment]
Sorry forgot to edit gaussian distribution definition on exercise 4.3

**Comment by lemonade5117** [comment]
Ahhh I messed up the notebook version number didn't I

**Comment by lemonade5117** [comment]
Still learning about git! 😅 Sorry to cause so much trouble, I fixed what I messed up. :)

**Comment by lemonade5117** [comment]
So a number of things I did wrong: I changed the version number to 3 again by accident, "fixed" hw1.jl when it was actually correct, and added a file called "1" because of some weird vim stuff😅 I fixed everything again now, everything should be fine. Sorry for the inconvenience :)

**Comment by lemonade5117** [comment]
I made a mistake with git so I reverted back. Everything should be good now 👍

**Comment by fonsp** [comment]
@leios

**Comment by fonsp** [comment]
Thanks!

**Pull request merged**
