### PR TITLE
Update DeployPage.yml

### PR DESCRIPTION
**Pull request by tlienart**
I saw that @fonsp was trying different stuff, this one should work without the SSH stuff (there was a bit of a debacle due to some update on the GitHub action front, anyway this one doesn't use SSH and should be fine).

### CODE REVIEW

**Comment by fonsp** [comment]
Looks fine but that secret does not exist, right?

**Comment by tlienart** [comment]
it's a GitHub token, it exists for everyone (this deploy script has been tested by multiple people moving away from the SSH one so it's pretty safe).

**Comment by fonsp** [comment]
Ah I see, cool!

**Comment by fonsp** [comment]
It worked, great! Sorry for questioning you 💆‍♀️, must be tedious to fix all those repositories

**Comment by fonsp** [comment]
@tlienart I have deleted the two secrets from our settings. Can we also safely delete the deploy key? I don't know what it does
https://github.com/mitmath/18S191/settings/keys

**Comment by tlienart** [comment]
Yes

**Pull request merged**
