### PR TITLE
remove need for PkgPage

### PR DESCRIPTION
**Pull request by tlienart**
This should "just-work", if it doesn't, just revert to 2c5f06c and ignore.  

The rationale is that you don't need PkgPage at all here (apart maybe for the path thing which can be written explicitly in the deploy).

### CODE REVIEW

**Comment by fonsp** [comment]
It didn't work :(

**Comment by fonsp** [comment]
https://github.com/mitmath/18S191/runs/1143740852?check_suite_focus=true#step:5:6

**Comment by tlienart** [comment]
sorry I forgot a semicolon

**Comment by tlienart** [comment]
ah crap I need to do another branch

**Comment by fonsp** [comment]
Sorry i have this funky browser extension that automatically clicks on "Delete branch"

**Comment by fonsp** [comment]
Still not working :(
https://github.com/mitmath/18S191/runs/1143787626?check_suite_focus=true#step:5:80

**Pull request merged**
