### PR TITLE
Add Embedded Video player for past/future lectures 

### PR DESCRIPTION
**Pull request by logankilpatrick**
@fonsp see working video example here: https://video.cs50.io/8rrHTtUzyZA?start=1

### CODE REVIEW

**Comment by logankilpatrick** [comment]
See here for details: https://cs50.readthedocs.io/video/#api

**Comment by fonsp** [comment]
This PR didn't work because, confusingly, [this](https://github.com/mitmath/18S191/pull/70/files#diff-1a6c1c17728d53fda4fc93801fd776b2d7a708a432362844cf7b70838a5d7bc8L145) is not our youtube macro (I guess it's outdated code), it's [this one](https://github.com/mitmath/18S191/blob/ea814f3ad34904f143f544cf3785c697174c3630/website/utils.jl#L30).

I ran the corrected version, but the iframes don't work:

image

This is because `video.cs50.io` only allows itself to be embedded on pages with domains: `cs50.harvard.edu cs50.yale.edu *.cs50.io`.


I looked into running a `video.computationalthingkin.io` site ourselves, it looks like it used to be open source, but it went closed-source last year: https://github.com/cs50/video.cs50.net

Maybe you can get in touch with them?

**Comment by logankilpatrick** [comment]
Just emailed David

**Comment by fonsp** [comment]
In our case we also want it to work on `http://localhost:*/`, so that you can see the videos when you run the notebook on your own computer. That might complicate things

**Comment by fonsp** [comment]
Is it just a static web app? Or are the restrictions there to limit the server load?

**Pull request merged**
